/********************************************************************
 * Autogenerated file, do not edit.
 *******************************************************************/

#ifndef __GATT_DB_H
#define __GATT_DB_H

#include "sli_bt_gattdb_def.h"

extern const sli_bt_gattdb_t gattdb;

#define gattdb_generic_attribute              1
#define gattdb_service_changed_char           3
#define gattdb_database_hash                  6
#define gattdb_client_support_features        8
#define gattdb_device_name                    11
#define gattdb_DataService                    12
#define gattdb_Data_TX                        14
#define gattdb_Data_RX                        17
#define gattdb_ota                            19
#define gattdb_ota_control                    21


#endif // __GATT_DB_H
